var exampledata = {
  "id": 345534,
  "title": "Game of Thrones",
  "original_title": "Game of Thrones",
  "plot_overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
  "type": "tv_series",
  "runtime_minutes": 60,
  "year": 2011,
  "end_year": 2019,
  "release_date": "2011-04-17",
  "imdb_id": "tt0944947",
  "tmdb_id": 1399,
  "tmdb_type": "tv",
  "genres": [
      40,
      7,
      39
  ],
  "genre_names": [
      "Action & Adventure",
      "Drama",
      "Sci-Fi & Fantasy"
  ],
  "user_rating": 8.8,
  "critic_score": 85,
  "us_rating": "TV-MA",
  "poster": "https://cdn.watchmode.com/posters/0345534_poster_w185.jpg",
  "backdrop": "https://cdn.watchmode.com/backdrops/0345534_bd_w780.jpg",
  "original_language": "en",
  "similar_titles": [
      315551,
      3101216,
      3129354,
      392023,
      519834,
      3143011,
      3119816,
      3135512,
      329319,
      3165325,
      383653,
      311767,
      3131293,
      36822,
      390013,
      3130921,
      52048,
      376191,
      317379,
      390217,
      385447,
      375443,
      3106167,
      3123483,
      3124749
  ],
  "networks": [
      1
  ],
  "network_names": [
      "HBO"
  ],
  "relevance_percentile": 99.03,
  "trailer": "https://www.youtube.com/watch?v=BpJYNVhGf1s",
  "trailer_thumbnail": "https://cdn.watchmode.com/video_thumbnails/680943_pthumbnail_320.jpg",
  "sources": [
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/episode/winter-is-coming/umc.cmc.11q7jp45c84lp6d16zdhum6ul?playableId=tvs.sbd.9001%3A494877461&showId=umc.cmc.7htjb4sh74ynzxavta5boxuzq",
          "format": "SD",
          "price": 2.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 349,
          "name": "iTunes",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://tv.apple.com/us/episode/winter-is-coming/umc.cmc.11q7jp45c84lp6d16zdhum6ul?playableId=tvs.sbd.9001%3A494877461&showId=umc.cmc.7htjb4sh74ynzxavta5boxuzq",
          "format": "HD",
          "price": 3.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&cdid=tvseason-0uaIRlgLkL4&gl=us&hl=en&id=71Edzxe9gmo",
          "format": "SD",
          "price": 2.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 140,
          "name": "Google Play",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.google.com/store/tv/show?amp=&cdid=tvseason-0uaIRlgLkL4&gl=us&hl=en&id=71Edzxe9gmo",
          "format": "HD",
          "price": null,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Game-of-Thrones-Winter-Is-Coming/296654",
          "format": "SD",
          "price": 2.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Game-of-Thrones-Winter-Is-Coming/296654",
          "format": "HD",
          "price": 3.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 307,
          "name": "VUDU",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.vudu.com/content/movies/details/Game-of-Thrones-Winter-Is-Coming/296654",
          "format": "4K",
          "price": 4.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.66a9f7b2-5fd9-b1aa-8e57-063077765f2d",
          "format": "SD",
          "price": 2.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 24,
          "name": "Amazon",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://watch.amazon.com/detail?gti=amzn1.dv.gti.66a9f7b2-5fd9-b1aa-8e57-063077765f2d",
          "format": "HD",
          "price": 3.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxmzkkj",
          "format": "SD",
          "price": 2.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 398,
          "name": "Microsoft Store",
          "type": "buy",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.microsoft.com/en-us/p/season-1/8d6kgwxmzkkj",
          "format": "HD",
          "price": 3.99,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 387,
          "name": "HBO MAX",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://play.hbomax.com/episode/urn:hbo:episode:GVU4NYgvPQlFvjSoJAbmL",
          "format": "HD",
          "price": null,
          "seasons": 8,
          "episodes": 73
      },
      {
          "source_id": 443,
          "name": "Spectrum On Demand",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://ondemand.spectrum.net/tv/hbo-max/8553063/game-of-thrones/",
          "format": "HD",
          "price": null,
          "seasons": 8,
          "episodes": 65
      },
      {
          "source_id": 385,
          "name": "HBO (Via Hulu)",
          "type": "sub",
          "region": "US",
          "ios_url": "Deeplinks available for paid plans only.",
          "android_url": "Deeplinks available for paid plans only.",
          "web_url": "https://www.hulu.com/watch/c6d4ecfc-8ffa-4776-9ec4-8a4bf4049bcc",
          "format": "HD",
          "price": null,
          "seasons": 8,
          "episodes": 73
      }
  ]
}

export default exampledata;